export enum TicketStatus {
  AI_RESOLVING = 'RESOLVIENDO_IA',
  RESOLVED_BY_AI = 'RESUELTO_IA',
  PENDING_AGENT = 'PENDIENTE_AGENTE',
  AGENT_RESOLVING = 'RESOLVIENDO_AGENTE',
  RESOLVED_BY_AGENT = 'RESUELTO_AGENTE',
}
